# Links
permalink: /:year/:month/:title
url: http://ideaflare.github.io

# About
title: Field Notes
tagline: Musings, usually around software.
description: Causes & effects in software development, and other observations/conclusions in general

# Disable excerpts(blog previews)
excerpt_separator: ""

# Number of Posts displayed per-page
paginate: 1

# Parsers
markdown: kramdown
highlighter: rouge

# Analytics
google_analytics: UA-80449036-1
