# Unknown
excerpt_separator: ""

# Dependencies ?
highlighter: rouge
markdown: kramdown

# Links
permalink: /blog/:pretty
url: http://ideaflare.github.io

# Setup
title: Software better
tagline: Causes & effects in software development
description: I'm captivated by the things that make software development fun & effective. This is where I share what I discover/think about becoming a better software developer, XP, Kaizen, FP, Lean, Craftsmanship, Anzeneering, etc.. 

# Unknown 2
paginate: 1

# Analytics
google_analytics: UA-80449036-1
