# Links
permalink: /:year/:month/:title
url: http://ideaflare.github.io

# About
title: Software better
tagline: Causes & effects in software development
description: I'm captivated by things that make software development fun & effective. This is where I share what I discover/think about good software development - XP, FP, Kaizen, Lean, Craftsmanship, Anzeneering, etc.. 

# Disable excerpts(blog previews)
excerpt_separator: ""

# Number of Posts displayed per-page
paginate: 1

# Parsers
markdown: kramdown
highlighter: rouge

# Analytics
google_analytics: UA-80449036-1
